name: CI

on:
  push:
    branches:
      - develop
  pull_request:

concurrency:
  group: develop-nex-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    name: Server

    services:
      redis-cache:
        image: redis:alpine
        ports:
          - 13000:6379
      redis-queue:
        image: redis:alpine
        ports:
          - 11000:6379
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: frappe
          POSTGRES_PASSWORD: frappe
          POSTGRES_DB: test_site
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-timeout 10s

    steps:
      - name: Clone
        uses: actions/checkout@v3

      - name: Find tests
        run: |
          echo "Finding tests"
          grep -rn "def test" > /dev/null

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          check-latest: true

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/*requirements.txt', '**/pyproject.toml', '**/setup.py', '**/setup.cfg') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: 'echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT'

      - uses: actions/cache@v4
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Setup
        run: |
          pip install frappe-bench
          bench init --skip-redis-config-generation --skip-assets --python "$(which python)" ~/frappe-bench

      - name: Install
        working-directory: /home/runner/frappe-bench
        run: |
          bench get-app nex $GITHUB_WORKSPACE
          bench setup requirements --dev
          # Retry new-site command
          for i in {1..5}; do
            # bench new-site --db-root-password frappe --admin-password admin --db-type postgres --db-host postgres --db-port 5432 --db-user frappe test_site && break || sleep 10
            bench new-site --db-root-password frappe --admin-password admin --db-type postgres --db-password frappe test_site && break || sleep 10
            if [ $i -eq 5 ]; then
              echo "Failed to create site after multiple retries"
              exit 1
            fi
          done
          bench --site test_site install-app nex
          bench build
        env:
          CI: 'Yes'

      - name: Run Tests
        working-directory: /home/runner/frappe-bench
        run: |
          bench --site test_site set-config allow_tests true
          bench --site test_site run-tests --app nex
        env:
          TYPE: server